### ISSUE TITLE
Cancel Drop

### ISSUE THREAD

**Issue by all4manu** [4teamwork/vue-drop-zone#3]
At the moment it seems like every time you drop a file onto the drop zone, it will try to upload it. There are however times when this behaviour should be prevented (i.e. when the upload would not succeed, or if some condition is not met).

The following two features might need to be added:
- It should be possible to cancel the upload inside the `dropped` method. This way it would be possible to check conditions and abort if they are not met.
- There should be an attribute like `canDrop` to prevent dropping a file altogether.

**Comment by elioschmutz** [comment]
@all4manu See #6 for more information about your requested feature.

It is already possible with an uppy confiugration. So there is no need to update the `vue-drop-zone`

**Comment by bierik** [comment]
@all4manu fixed this with a workaround.
